### ISSUE TITLE
Translations / Multiple language support

### ISSUE THREAD

**Issue by drewbitt** [PoiScript/HoloStats#218]
For web

**Comment by PoiScript** [comment]
Thanks for suggestion! I'm also glad to implement i18n for holostats. :)

**Comment by PoiScript** [comment]
I had translated some content to English:

![Screenshot_2020-04-25 HoloStats(1)](https://user-images.githubusercontent.com/17513314/80275519-585ff200-8714-11ea-8a64-5ef003f9ca78.png)

The browser should automatically determine the language to be displayed, and you can change it manually by clicking the first button in the top right corner.

**Comment by PoiScript** [comment]
And I'm still looking for a solution to display different vtuber name under different languages, (e.g 白上フブキ -> Fubuki Shirakami).

**Comment by drewbitt** [comment]
Works great, thanks for being so quick with my request! Also of note, settings is not translated.

**Comment by PoiScript** [comment]
vtuber name is now translated too:

![image](https://user-images.githubusercontent.com/17513314/80302543-32525480-87dd-11ea-9bae-bb9d7c160750.png)

**Comment by PoiScript** [comment]
This issue was considered resolved. Closing :)
