### ISSUE TITLE
Disappearing videos

### ISSUE THREAD

**Issue by krisszt** [PoiScript/HoloStats#359]
Hello!

I was looking for a video but I couldn't find it on your site, and also realised there should be two thumbnails that are copies of each other but I found only one, a little search later I found them ([V1](https://www.youtube.com/watch?v=vrJJyXLLja8), [V2](https://www.youtube.com/watch?v=3QJD9iekpDQ)) and indeed they are not available.

And I had found [another](https://www.youtube.com/watch?v=qYRW8XJSv18) as I was writing this after comparing with [their own schedule](https://schedule.hololive.tv/lives/hololive).

Hope I had pointed out something new.

**Comment by PoiScript** [comment]
Sorry for the delayed response. Unfortunately, I cannot find any of these videos on my database. Feel free to reopen this if you want to know something more.
