### ISSUE TITLE
Rogue video under YouTube schedule page

### ISSUE THREAD

**Issue by mlturner88** [PoiScript/HoloStats#368]
Hello, thanks for the great app/site. I've noticed for around a month or more now there is this rogue video "scheduled" in the past for Roboco. Not sure if that is just me or not but I figured I would report it. Thanks!

![image](https://user-images.githubusercontent.com/6932385/97013440-107d2480-1517-11eb-93a8-193bf2dac286.png)

**Comment by PoiScript** [comment]
Thanks you for reporting this. The stream should be gone now.
