### ISSUE TITLE
Again, streams are not registered, even the scheduled ones.

### ISSUE THREAD

**Issue by Secmess** [PoiScript/HoloStats#505]
All of these streams today, all were scheduled streams, are not registered in your website.

- https://www.youtube.com/watch?v=tEz9DXN57XE
- https://www.youtube.com/watch?v=O9NDwqo6_AY
- https://www.youtube.com/watch?v=4ieyz_mFw-A

I wonder how many streams did I miss because of this.

**Comment by Secmess** [comment]
I think today is particularly bad. 7 currently streaming, and this website only detected 2 at the time I took this screenshot.

![image](https://user-images.githubusercontent.com/24835551/109290816-af65b480-785a-11eb-99e2-974d2f3de071.png)

![image](https://user-images.githubusercontent.com/24835551/109290835-b7255900-785a-11eb-829c-b0bb770e9f86.png)

**Comment by PoiScript** [comment]
Thanks you for reporting this. I guess it was caused by youtube pubsubhubbub. I will try to bring back the old strategy and see if it can help.
