### ISSUE TITLE
About HoloStats Views

### ISSUE THREAD

**Issue by JC-Chung** [PoiScript/HoloStats#525]
It seems have something error about views and related Last Day(s)

https://i.imgur.com/rhZyLYx.png
https://i.imgur.com/oxuxNi9.png
https://i.imgur.com/FNg1gj3.png
https://i.imgur.com/U8VbvgV.png
https://i.imgur.com/GmaudH4.png

Even have this
https://i.imgur.com/FTOnH6O.png

Sorry my English is not good

**Comment by PoiScript** [comment]
你可以使用中文進行留言。

> It seems have something error about views and related Last Day

你指的是 YouTube 頻道的訂閱人數嗎？實際上，YouTube 目前只會顯示頻道的訂閱人數的粗略值： https://support.google.com/youtube/answer/6051134?hl=zh-Hant 。如果頻道日增加的訂閱者沒有超過該閾值，就會顯示為 0。

**Comment by JC-Chung** [comment]
> 你可以使用中文進行留言。
> 
> > It seems have something error about views and related Last Day
> 
> 你指的是 YouTube 頻道的訂閱人數嗎？實際上，YouTube 目前只會顯示頻道的訂閱人數的粗略值： https://support.google.com/youtube/answer/6051134?hl=zh-Hant 。如果頻道日增加的訂閱者沒有超過該閾值，就會顯示為 0。

指的是觀看數部分，可以發現總數、日增跟週增都沒有變動，只有月增有變動。
而在之前3/4 6:00的數據(最下方一張)，甚至有日增全員為0，僅Calli為600萬日增。
目前的這三欄數據也不是每小時更動，只有月增在變。

**Comment by PoiScript** [comment]
該 issue 信息有點過期了，如果問題依然存在，可以另起一個 issue。
