### ISSUE TITLE
Can't open HoloStats anymore

### ISSUE THREAD

**Issue by Watakun7** [PoiScript/HoloStats#534]
It happened in the last few hours. I can see only this:

[https://imgur.com/a/UykBJtg](https://imgur.com/a/UykBJtg)

Is it a cache issue or something else?

P.S. I love this tool, you did a great job

EDIT: No, it's not a cache issue, I had the same result in a fresh installation of Firefox.

**Comment by PoiScript** [comment]
Sorry for the inconvenience! I forgot to set the default language, so HoloStats will crash for unsupported languages (in your case, french). I just fixed the problem. Please try again and let me know if you still have any issues.

**Comment by Watakun7** [comment]
It works again, thank you! :)
