### ISSUE TITLE
請問您有是否有興趣製作新增其他公司和個人vtuber的相關數據與資訊?

### ISSUE THREAD

**Issue by IGA3830** [PoiScript/HoloStats#535]
首先非常感謝您製作出holostats,他在顯示和紀錄vtuber相關資料上真的非常好用且美觀,
想請問您有興趣加入彩虹社,774 inc.等其他公司或者其他還沒列入較知名的個人vtuber?

**Comment by PoiScript** [comment]
很抱歉，目前沒有添加其他太多非 hololive vtuber 的打算。如果有需要的話可以嘗試 self-hosted。
