### ISSUE TITLE
Bug? Stream duration is still going up.

### ISSUE THREAD

**Issue by krisszt** [PoiScript/HoloStats#558]
Noel's [MonHun stream](https://holo.poi.cat/stream/Q_sZ7DvyRIk) is still shown as ongoing despite it being otherwise. My guess is the issue comes from youtube banning/deleting it as it was live.

EDIT: 04/20, the stream has been reinstated and everything went back to normal.

**Comment by PoiScript** [comment]
Thanks you for report this. The problem seems to be solved. Closing now. Feel free to reopen.
