### ISSUE TITLE
A suggestion for parsing Youtube subscriptions

### ISSUE THREAD

**Issue by linnil1** [PoiScript/HoloStats#582]
The `channel_stat` will give out error when the subscription is intentionally hided by channel owner,
though that's not the case for Hololive.

I change the `subscriber_count` to an optional field in these two lines: 
https://github.com/PoiScript/HoloStats/blob/master/server/src/requests/channels.rs#L34
``` diff
-  subscriber_count:  String,
+  subscriber_count:  Option<String>,
```
https://github.com/PoiScript/HoloStats/blob/master/server/src/requests/channels.rs#L74
``` diff
- subscriber_count: i32::from_str(&channel.statistics.subscriber_count).unwrap(),
+ subscriber_count: i32::from_str(&channel.statistics.subscriber_count.unwrap_or(String::from("0"))).unwrap(),
```
Shall I PR?

**Comment by linnil1** [comment]
> Would you mind providing the channel id? I want to see the actually response data from youtube api.

Here is the example(python):

channid="UC7VNrZqdH_t8dLMdrp0NrJQ"
``` ipython
In [11]: httpx.get("https://www.googleapis.com/youtube/v3/channels", 
                   params={'part': "statistics", 
                           'key': apikey,
                           'id': "UC7VNrZqdH_t8dLMdrp0NrJQ", 
                           'fields': "items(id,statistics(viewCount,subscriberCount))"}).json()
Out[11]: 
{'items': [{'id': 'UC7VNrZqdH_t8dLMdrp0NrJQ',
            'statistics': {'viewCount': '26491'}}]}
```

> So you're running your own instance of HoloStats, right?

Yes, I use this great framework to show the statistic of Taiwan vtubers.
The description and URL are written in README and modified code are public in my fork repo.

> Feel free to, and i suggest using unwrap_or_default which is more "rustic": i32::from_str(&channel.statistics.subscriber_count).unwrap_or_default()

Thanks a lot. I'm very new to Rust.

**Comment by PoiScript** [comment]
I just updated code to handle empty subscriber count. It should works now.


> Yes, I use this great framework to show the statistic of Taiwan vtubers.
> The description and URL are written in README and modified code are public in my fork repo.

I recently created a new repo: https://github.com/PoiScript/HoloStats-deploy which help to deploy HoloStats server.

It contains all precompiled binaries and an example configuration file (yes, no more hard-coded environment variables). And all you have to do is to setup your environment and create your own configuration file (run `cp holostats.example.toml holostats.toml` and modify to suit your needs).

Please took a look. Any ideas will be appreciated.
