### ISSUE TITLE
Aoi Nabi, Amelia's illustrator, new vtuber

### ISSUE THREAD

**Issue by krisszt** [PoiScript/HoloStats#583]
Amelia's illustrator, Aoi Nabi, has started [streaming on her channel](https://www.youtube.com/channel/UCzKkwB84Y0ql0EvyOWRSkEw) (also can be found on [twitter](https://twitter.com/nab0i), [pixiv](https://pixiv.me/uz02) and [tumblr](https://n-abi.tumblr.com/)), and right afterwards Ame was asked if a collab is coming and [she said it's possible](https://youtu.be/et8HYdSoQ-Q?t=409). (With Nabi answering a [collab is possible](https://youtu.be/PJmtcnbv7XU?t=811), too (CC subbed [clip](https://www.youtube.com/watch?v=DzoqMwjVe2Q)).)

Since it seems collabs are in the future I would like her to be added into the "Others" tab.

**Comment by PoiScript** [comment]
Added.
