### ISSUE TITLE
Nabi's timer is still going upwards

### ISSUE THREAD

**Issue by krisszt** [PoiScript/HoloStats#594]
[Nabi's stream](https://holo.poi.cat/stream/OkEqYTdnhf8) is still shown as [ongoing](https://imgur.com/a/Uq5cgnx), despite it being privated.

Like Noel's stream earlier ( #558 ) but I feel this time the video won't be reinstated to inadvertently solve the issue here (if that's what happened there).

**Comment by PoiScript** [comment]
Thank you for reporting. I just updated the data and the timer should get back to normal.

I'll look to the problem. I guess it happens because stream was deleted or made private while still streaming.
