### ISSUE TITLE
Inconsistency and missing numbers for streams.

### ISSUE THREAD

**Issue by Xynaps** [PoiScript/HoloStats#623]
Hi, not sure how supported the project is at the moment but currently there seems to be an ongoing issue with the live tracking of streams at times. It seems to affect most if not all streams during that time.

Since it seems to  be from time to time and not a constant issue I guess it's either due to quota limits towards the Youtube api or some issues during any potential maintenance.

**Comment by PoiScript** [comment]
Sorry for the delay, the should be solved now.
