### ISSUE TITLE
Feature Request: Connect Youtube Account and Add/Remove streams to Watch Later

### ISSUE THREAD

**Issue by shoaibshakeel381** [PoiScript/HoloStats#723]
Can you please add feature to allows user's to signin to their youtube account and add/remove streams to Watch Later?

**Comment by PoiScript** [comment]
I am not sure if it will work and I need to investigate. I will give you an update when I get more information

**Comment by PoiScript** [comment]
According to this [revision history](https://developers.google.com/youtube/v3/revision_history#september-9,-2020), you cannot update the WatchLater list of users. Instead, you have to specify a playlist.

<img width="924" alt="Screen Shot 2021-12-31 at 6 17 48 PM" src="https://user-images.githubusercontent.com/17513314/147817755-d80aa2e6-38a9-4657-81b1-ac407dabc724.png">

**Comment by shoaibshakeel381** [comment]
This makes implementations more involved. 

Basically when user clicks on 'Add to Playlist' button, we show all their playlists and then they can add it to any playlist they like. I think various youtube apps also use similar apis.

**Comment by shoaibshakeel381** [comment]
Maybe this can help:
https://stackoverflow.com/questions/42513339/add-video-to-users-watch-later-playlist-on-youtube

**Comment by PoiScript** [comment]
> Maybe this can help: https://stackoverflow.com/questions/42513339/add-video-to-users-watch-later-playlist-on-youtube

Unfortunately, the answer was outdated. You cannot insert video into users' watch later playlist anymore.

![image](https://user-images.githubusercontent.com/17513314/148153532-bca0fa82-749e-40d5-a743-e3628a2f6eeb.png)

**Comment by PoiScript** [comment]
I added an initial support of youtube playlist at https://yt-playlist.holostats.pages.dev/.

Go to /settings, click `Sign In`, and now you can add stream directly to playlist by clicking the second button on thumnail

<img width="717" alt="Screen Shot 2022-01-05 at 11 44 27 AM" src="https://user-images.githubusercontent.com/17513314/148157472-7f75ffb7-84b6-44ec-877b-613dd8ab5705.png">


 Google might complain that it's unverified app, I'll see if I can pass verification before making it public.

![image](https://user-images.githubusercontent.com/17513314/148152982-e842e4c6-5c21-4cfc-adfb-bd7acb7f3243.png)

**Comment by shoaibshakeel381** [comment]
oh wow, that looks great. I tried it and it does work. BTW looks like that playlist selector drowndown only shows 5 playlists, for me it only showed 5 private ones. Is this intentional or a bug

**Comment by shoaibshakeel381** [comment]
ok from google docs it looks like results are paginated and a single page length depends on `maxResults` filter which is 5 by default. it accepts a maximum of 50. Maybe we can change playlist fetching logic to something like below:
(Excuse my bad code, I don't know much about javascript.)

```js
private listPlaylist(pageToken: string): Observable<YouTubePlaylistResponse> {
  let parameters = new HttpParams()
  .set("mine", "true")
  .set("maxResults", "50")
  .set("part", "snippet,contentDetails,id,localizations,status");

  if (pageToken){
    parameters.set("pageToken", pageToken)
  }

  return this.http.get<YouTubePlaylistResponse>(
    "https://youtube.googleapis.com/youtube/v3/playlists",
    {
      headers: {
        Authorization:
          "Bearer " +
          gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse(true)
            .access_token,
      },
      params: parameters,
    }
  );
}

async listAllPlaylists(): Observable<YouTubePlaylistResponse> {
  let allPlaylists: YouTubePlaylistResponse[] = [];
  let nextPage: string = null;

  do {
    const response = await this.listPlaylist(nextPage).toPromise();
    allPlaylists.push(response);

    nextPage = response.nextPageToken;
  } while(nextPage != null);

  return allPlaylists;
}

```

**Comment by PoiScript** [comment]
I had set the `maxResults` to 50 now, it should be enough for most people. And according to google team, I need to publish the code to production environment before getting verification. Hence you can now try it on https://holo.poi.cat.

**Comment by PoiScript** [comment]
Finally got a verification from google! And this issue can now be marked as done. :) Feel to open another one if you encounter any problems!

![image](https://user-images.githubusercontent.com/17513314/149709564-ef203dae-71b9-4786-a62e-05b07dab1fe0.png)

**Comment by shoaibshakeel381** [comment]
@PoiScript BTW just to let you know, we can add same video more that once to same playlist. Maybe in future we will have to fict check if video is already added or not

**Comment by PoiScript** [comment]
@shoaibshakeel381, yes, it seems like that I have to dedup the playlist after adding new videos. I opened a new issue https://github.com/PoiScript/HoloStats/issues/801 for tracking.
