### ISSUE TITLE
Auto detect and delete non-existing streams from database

### ISSUE THREAD

**Issue by shoaibshakeel381** [PoiScript/HoloStats#724]
`/youtube-stream` page still shows streams which have been removed. Is it possible to auto remove them from your database as automatically?

[Sample Image](https://i.imgur.com/plc6iTE.png)

Currently I'm using a user-script to hide them. but it would be awesome to fix this in site as well.

**Comment by PoiScript** [comment]
This issue should by fixed by commits 66136b157eac2ce9924622062e1ca4205d4f8907 and b1df8d0e44d25b5e4a986fd5a1a2f1bbcb739f30.

Feel to reopen if you still see any non-existent stream.
