### ISSUE TITLE
Like Count History

### ISSUE THREAD

**Issue by fxavierho123** [PoiScript/HoloStats#741]
Since Youtube have shit on the Live Viewer count at around 26th Dec onward, the live viewer count is not that relevant anymore. I suggest adding a Like count history for each video for better knowing how much viewer is actually watching the live stream. To further enhance the prediction, you can even add the youtube view count history right after the stream have ended, but that maybe too much for now. 

p.s. If you don't know this issue, you can check out 【3DLIVE】この叫びを届けるためにｰScreamｰ【#常闇トワ2周年記念】vs 【3DLIVE】桃鈴ねね x 星街すいせい x 常闇トワ　Christmas Live【 #ねねすいトワクリスマスライブ 】Live viewer number history + total comment number. 

Also, the proof of the vote court surpass live view court in 2 mins https://twitter.com/TeamYouTube/status/1477191674661122050

I can explain further if anyone need more explaination

**Comment by PoiScript** [comment]
I had add a like count history for newly created stream and it now only records when stream is live. I think it's enough for now, let me know if you think differently.
