### ISSUE TITLE
Feature request: Vtuber hyperlink on stream/schedule page

### ISSUE THREAD

**Issue by fgsfdss** [PoiScript/HoloStats#747]
Quite simply, it would be useful if the profile picture and/or name were clickable with a link to the respective /vtuber page, to more quickly see their past streams and other activity. Saves one click.

**Comment by PoiScript** [comment]
Do you mean the profile image below stream thumbnail? 

![image](https://user-images.githubusercontent.com/17513314/149383423-499ccc8c-1b60-478e-92e9-040405d787f5.png)

**Comment by PoiScript** [comment]
Sorry, I forgot to read the title

**Comment by fgsfdss** [comment]
Speed. Thanks!
