### ISSUE TITLE
Hasn't been updated since 9th March?

### ISSUE THREAD

**Issue by DanielKHL** [PoiScript/HoloStats#811]
![image](https://user-images.githubusercontent.com/42729950/167772385-37437e02-dcfa-4cfe-a676-49a7268b851d.png)

**Comment by PoiScript** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Never](https://trello.com/c/SKGfzoU1/5-never)

**Comment by PoiScript** [comment]
Sorry for the delayed response, the issue should be resolved now.
