### ISSUE TITLE
自 2022/07/16 20:40 (UTC+8) 後無法取得數據、500 INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by JC-Chung** [PoiScript/HoloStats#813]
2022/07/16 20:20 (UTC+8) 仍可正常取得數據

4 個分頁皆無法取得資料，並在 30秒後回傳 code 500

`{"code":500,"message":"INTERNAL_SERVER_ERROR"}`

**Comment by PoiScript** [comment]
Thank you for reporting this issue. Just restarted the service and everything seems to work find. No data loss.
