### ISSUE TITLE
There are errors in some parts of the website.

### ISSUE THREAD

**Issue by gcobc12632** [PoiScript/HoloStats#841]
All the following questions come from this website "https://vt.poi.cat/channel/subscribers".

1. The subscription data has not been updated, and the data seems to have stopped a month ago.
![1](https://github.com/vtstats/web/assets/31128599/3d0e9a83-83da-4f1c-8469-37d8e5d32a15)
![1-2](https://github.com/vtstats/web/assets/31128599/62358122-3917-4d3c-8ae0-f15cf4bf1440)

2. Any live broadcast data on the personal page, the link of the cover has become "https://vt.poi.cat/()=%3E%7Bif(Wg(r),Gg(r),r.value===As)throw%20r.error;return%20r.value%7D", not the link of the live broadcast.
![2](https://github.com/vtstats/web/assets/31128599/cf66be0e-fed5-4e70-b6af-5b8dbd28c011)

**Comment by Zei33** [comment]
Also the revenue data appears to be inaccurate. Last 30, 7 and 1 day numbers are inconsistent, with last 30 often showing the lowest number when it should include the number of the other two.

Take Marine for example

Last Day - AU$11,298
Last 7 Days - AU$28,401
Last 30 Days - AU$19,146

The last 30 days number should be higher than the last 7 days. Unless you're not including the numbers of the more recent periods for some reason.

My guess is line 119 to 129 in https://github.com/vtstats/web/blob/a/src/app/pages/channel-stats/channel-stats.ts

```ts
if (stats.kind === ChannelStatsKind.REVENUE) {
  const value = sum(stats.value);
  acc.push({
    vtuberId: channel.vtuberId,
    value,
    delta1d: value - sum(stats.value1DayAgo),
    delta7d: value - sum(stats.value7DaysAgo),
    delta30d: value - sum(stats.value30DaysAgo),
  });
}
```

He defines the type

```ts
export type ChannelStatsSummary =
| {
    channelId: number;
    kind: ChannelStatsKind.REVENUE;
    value: Record<string, number>;
    value1DayAgo: Record<string, number>;
    value7DaysAgo: Record<string, number>;
    value30DaysAgo: Record<string, number>;
  }
```

I really have no idea what the values for `stats.value30DaysAgo` is but I'm guessing it's a key, value pair of the payments in that range (as per the `sum()` function definition).

Unfortunately I'm just not familiar enough with Angular to figure out where `query()` is getting the data from. Sorry I can't submit a solution.

**Comment by gcobc12632** [comment]
The error in the subscription count seems to have been corrected.

**Comment by PoiScript** [comment]
Hi @gcobc12632. Apologies for the delay. Both issues should be resolved now. If you face any further problems, please open a new ticket.
