### ISSUE TITLE
Adding missing Vtuber entries

### ISSUE THREAD

**Issue by LiquidRekto** [PoiScript/HoloStats#857]
The list have been quite outdated for a while, so I will add in some more vtubers to the list.

More information can be get through this website: https://virtualyoutuber.fandom.com/wiki/Virtual_YouTuber_Wiki

#New Group: Phase Connect

##Phase Connect
**Official Channel: Phase Connect**
YT id: UClpOEZoIYhxIY6n5NNGaPbA
Twitch id: 738651384

Which includes 2 subgroups

##Phase Connect

Which also contains following groups:

###Phase OriginS
Which includes:
**Rinkou Ashelia**
YT id: UCg7sW-h1PUowdiR5K4HlBew
Twitch id: 664168605

**Utatane Nasa**
YT id: UCB7sSUNwh_dXE7ZL3DsGDpw
Twitch id: 741953919

**Pipkin Pippa**
YT id: UCJ46YTYBQVXsfsp8-HryoUA
Twitch id: 664173845

**Tenma Maemi**
YT id: UC3K7pmiHsNSx1y0tdx2bbCw
Twitch id: 664177022

**Hakushika Iori**
YT id: UCN5bD1YYapThOeadG7YkBOA
Twitch id: 673848629

**Fujikura Uruka**
YT id: UCjXJYPsKxoJyc-1RPB6dSyw

**Shisui Michiru**
YT id: UC1cExET9xoWSO9iSnRsW_1Q
Twitch id: 677369149

###Phase Invaders
Which includes:

**Kaneko Lumi**
YT id: UCx_zwZuGIS4jxO07kFk8G6Q
Twitch id: 694413391

**Dizzy Dokuro**
YT id: UC98iRMvRqUxRD6GP4NtRskw
Twitch id: 560113344

**Jelly Hoshiumi**
YT id: UCkb-r702uhx4-6Lrmetp-Ow
Twitch id: 76447966

**Ember Amane**
YT id: UC0w_dvkIwnXzMak6gfeioRQ
Twitch id: 600084675

###Phase ALiAS
Which includes:

**Remilia Nephys**
YT id: UC-hMwvRuMsQrfgu0DPKLV2A
Twitch id: 823001288

**Chisaka Airi**
YT id: UC5qlAhrec6-0J-K3zmhNPPQ

**Amanogawa Shiina**
YT id: UCnJNNk45O1QYS2oMRYFKSyw
Twitch id: 801786062

**Himemiya Rie**
YT id: UCJ4O6PWA47f6XbCgrLQNqEQ
Twitch id: 801785761

**Makina Erina**
YT id: UCupmjRr7kPgzXKh-cPxxGbg

**Komachi Panko**
YT id: UCVo_KgPNsDKxHwzib7uarCw
Twitch id: 776677491

###Phase Euphoria
Which includes:

**Saya Sairroxs**
YT id: UCFzQd4pZ43ZNEdWBFe7QOKA

**Hikanari Hina**
YT id: UCXDytlJU6RL8D68VrPZGyIA

**Runie Ruse**
YT id: UCoAQsc-DQ0MjfTp059otQAw

**Muu Muyu**
YT id: UCejbicoRnQjCOdAPAv5JPwg

**Eimi Isami**
YT id: UC-tBLCGTheczDn5mYNoNWTQ

##Phase Connect JP
**Official Channel: Phase Connect JP**
YT id: UC6W1rDne4LOYK4XLpvhW6ow

Which also includes subgroups like:

###Phase KALEiDO
Which includes:

**Kannagi Loki**
YT id: UCucJYLJSEFRRfV2CA_JGHIQ

**Ayase Yuu**
YT id: UCnNLZWjl4GvVF4s8zBT9_kA
Twitch id: 1014863875

**Kaminari Clara**
YT id: UCRlZaszk84YXjRtdPCxqjvw
Twitch id: 1014863495

**Kokoromo Memory**
YT id: UCGXwv2zYOxeWiNNyPiLCBCQ
Twitch id: 1014911918

**Gram Pico**
YT id: UCtWH0tVAcUcSm4v96H5cAqQ

#Update: Vshojo
New Vtuber: 
**Michi Mochievee**
YT id: UCnS5IYNyGKOti9cFlK5SefQ
Twitch id: 1057785822

#Update: Others
New Vtuber entries:

**Maid Mint**
YT id: UCcHHkJ98eSfa5aj0mdTwwLQ

**Quinn Benet**
YT id: UC4l167H4Ef22ouZTV4-IVxg
Twitch id: 135407667

**Sayu Sincronisity**
YT id: UCYX_iGrhBnFt0dyXwSi7U4Q
Twitch id: 52668922

**Bao The Whale**
YT id: UCZQ7nZ8Lc7pslBN0gN1Jg0w
Twitch id: 110059426

**Sinder**
YT id: UC4dSp0pH0jfntIfKmlbw_BQ
Twitch id: 617455187

**Shoto**
YT id: UCgwJ4ReZqFOw_Y6eTEIunDQ
Twitch id: 119407348

**Shylily**
YT id: UCFnXTeBpJRPSN6QmWz_uDgQ
Twitch id: 100901794

**filian**
YT id: UCvjNdLLy5sinqD92Axk8w-g
Twitch id: 198633200

**Trickywi**
YT id: UCUJOS59EpFKPZWqCHEPeYeA
Twitch id: 63054799

**Comment by amicus-veritatis** [comment]
I also request to add Mikeneto into the entries:

## Mikeneko
Native name: `みけねこ`
Japanese name: same as above
English name: `Mikeneko`
Group: Others
Twitter username: `95rn16`
YT id: `UC54JqsuIbMw_d1Ieb4hjKoQ`
twitch: N/A
Bilibili: `3546644974930059` (I dunno this is a `platformId` or other kind of identifier for her social media on bilibili. [But she did stream on there](https://live.bilibili.com/32331141))
Status: Not retired

**Comment by amicus-veritatis** [comment]
> #New Group: Phase Connect
> 
> ##Phase Connect
>**Official Channel: Phase Connect** YT id: UClpOEZoIYhxIY6n5NNGaPbA Twitch id: 738651384
> 
> Which includes 2 subgroups

`Phase Connect`(All except kaleido with three members whose primary language of streaming is Japanese) and `Phase Connect JP`(Kaleido, with one member whose primary language of streaming is English), on some wiki the former is listed as `Phase-Connect`.

> ##Phase Connect

JP name: `フェーズコネクト`

> Which also contains following groups:

> ###Phase OriginS 

gen 1

>Which includes: 
>**Rinkou Ashelia** YT id: UCg7sW-h1PUowdiR5K4HlBew Twitch id: 664168605

JP name: `鈴香アシェリア`

> **Utatane Nasa** YT id: UCB7sSUNwh_dXE7ZL3DsGDpw Twitch id: 741953919

JP name: `転寝ナサ`, she primarily streams in Japanese;

> **Pipkin Pippa** YT id: UCJ46YTYBQVXsfsp8-HryoUA Twitch id: 664173845

JP name: `ピップキンピッパ`, no space nor interpunct in between, which is odd

> **Tenma Maemi** YT id: UC3K7pmiHsNSx1y0tdx2bbCw Twitch id: 664177022

JP name: `天満マエミ`

> **Hakushika Iori** YT id: UCN5bD1YYapThOeadG7YkBOA Twitch id: 673848629

JP name: `白鹿いおり`, she primarily streams in Japanese

> **Fujikura Uruka** YT id: UCjXJYPsKxoJyc-1RPB6dSyw

JP name: `藤倉ウルカ`

> **Shisui Michiru** YT id: UC1cExET9xoWSO9iSnRsW_1Q Twitch id: 677369149

JP name: `紫翠みちる`, she primarily streams in Japanese

> ###Phase ALiAS

gen 2

>Which includes:
> 
> **Remilia Nephys** YT id: UC-hMwvRuMsQrfgu0DPKLV2A Twitch id: 823001288

JP name: `レミリア・ネフィス`

> **Chisaka Airi** YT id: UC5qlAhrec6-0J-K3zmhNPPQ

JP name: `千坂アイリ`

> **Amanogawa Shiina** YT id: UCnJNNk45O1QYS2oMRYFKSyw Twitch id: 801786062

JP name: `天ノ川しいな`

> **Himemiya Rie** YT id: UCJ4O6PWA47f6XbCgrLQNqEQ Twitch id: 801785761

JP name: `姫宮りえ`

> **Makina Erina** YT id: UCupmjRr7kPgzXKh-cPxxGbg

JP name: `エリナ・マキナ`

> **Komachi Panko** YT id: UCVo_KgPNsDKxHwzib7uarCw Twitch id: 776677491

JP name: `小町ぱんこ`
 
> ###Phase Euphoria

Gen 3

>Which includes:
>
> **Saya Sairroxs** YT id: UCFzQd4pZ43ZNEdWBFe7QOKA

JP name: `サヤ・サイロクサス`

> **Hikanari Hina** YT id: UCXDytlJU6RL8D68VrPZGyIA

JP name: `光鳴ひな` 

> **Runie Ruse** YT id: UCoAQsc-DQ0MjfTp059otQAw

JP name: `ルニ・ルーズ`

> **Muu Muyu** YT id: UCejbicoRnQjCOdAPAv5JPwg

JP name: `むうむゆ`

> **Eimi Isami** YT id: UC-tBLCGTheczDn5mYNoNWTQ

JP name: `勇エイミ`

> ###Phase Invaders

not a gen

>Which includes:
> **Kaneko Lumi** YT id: UCx_zwZuGIS4jxO07kFk8G6Q Twitch id: 694413391

JP name: `金子瑠美`

> **Dizzy Dokuro** YT id: UC98iRMvRqUxRD6GP4NtRskw Twitch id: 560113344

JP name: N/A

> **Jelly Hoshiumi** YT id: UCkb-r702uhx4-6Lrmetp-Ow Twitch id: 76447966

JP name: `星海ジェリー`

> **Ember Amane** YT id: UC0w_dvkIwnXzMak6gfeioRQ Twitch id: 600084675

JP name: `エンバー天音`

Also

* Fuura Yuri
  * terminated at Apr 24, 2023
  * JP name: `ふうら百合`

> ##Phase Connect JP
>**Official Channel: Phase Connect JP** YT id: UC6W1rDne4LOYK4XLpvhW6ow 
> ###Phase KALEiDO
>Which includes:
> **Kannagi Loki** YT id: UCucJYLJSEFRRfV2CA_JGHIQ

JP name: `巫ロキ`

> **Ayase Yuu** YT id: UCnNLZWjl4GvVF4s8zBT9_kA Twitch id: 1014863875

JP name: `絢世ユウ`

> **Kaminari Clara** YT id: UCRlZaszk84YXjRtdPCxqjvw Twitch id: 1014863495

JP name: `歌美鳴クララ`, she primarily streams in English

> **Kokoromo Memory** YT id: UCGXwv2zYOxeWiNNyPiLCBCQ Twitch id: 1014911918

JP name: `恋衣めもり`

> **Gram Pico** YT id: UCtWH0tVAcUcSm4v96H5cAqQ

JP name: `倉夢ぴこ`

**Comment by PoiScript** [comment]
most vtuber were added now, It took a lot longer than I thought. 

I just created an issue template for adding new vtuber/group, and it should be more time-efficient next time.
