### ISSUE TITLE
Fix Vtuber issues

### ISSUE THREAD

**Issue by LiquidRekto** [PoiScript/HoloStats#863]
There are some Vtubers having this issue: 
When the Name Language is set to English, the result is this:
![image](https://github.com/vtstats/web/assets/46742676/994999c4-1cf7-4482-8b56-25f69544a5fb)

While switching to Japanese, still the same vtuber, the result is this:
![image](https://github.com/vtstats/web/assets/46742676/e91ead99-2aa3-4aac-a22b-5d03a4c515e5)

This issue might come from the database.

From what I've found, this is the list of Vtubers that have been affected by this:
**Kaneko Lumi - Phase Connect
Ayase Yuu - Phase Connect**

Also, for the Vtuber Michi Mochievee, please change her from **Others** to **Vshojo**

**Comment by amicus-veritatis** [comment]
```json
{"vtuberId":"kaneko-lumi","nativeName":"Kaneko Lumi","englishName":"金子瑠美","thumbnailUrl":"https://holos3.poi.cat/streams/thumbnail/kaneko-lumi.jpg","twitterUsername":"kaneko_lumi"}
```

```json
{"vtuberId":"ayase-yuu","nativeName":"絢世ユウ","japaneseName":"Ayase Yuu","thumbnailUrl":"https://holos3.poi.cat/streams/thumbnail/ayase-yuu.jpg","twitterUsername":"ayaseyuuu"}
```

Just checked the api catalog and it seems like a data entry issue.

**Comment by PoiScript** [comment]
thanks for reporting! both entries have been fixed.
