### ISSUE TITLE
Small issues with VTuber names or categories in settings

### ISSUE THREAD

**Issue by satsuki-sama** [PoiScript/HoloStats#870]
* Michi Mochievee should be in VShojo, not Others.
* Mint Fantôme's native/English name should be Mint Fantôme instead of katakana. Her Japanese and English names appear to be reversed. Her English name should be native.
* あおぎり高校 should probably have an English name in English mode.
* Hololive is officially styled "hololive" in lowercase, although this is often ignored.
* Holostars is officially styled "HOLOSTARS" in uppercase, although this is often ignored.
* HOLOSTARS English is a subset of -Tempus-, but it should be a subset of Holostars.
* Fuwamoco is properly styled FUWAMOCO.
* The name "Hololive EN Advent" should probably be "Hololive English -Advent-" for consistency with the other generations.
* Some hololive English generations have numbers after them (Advent, Promise) but the others do not, which is inconsistent.
* The Japanese names for the hololive English generations Advent and Promise still say "Hololive" instead of the katakana like the earlier EN generations.
* Fuwamoco's Japanese name should probably be katakana.
* Holostars English -ARMIS- lack Japanese names.

**Comment by PoiScript** [comment]
thanks for your suggestions! all issues regarding vtuber names are addressed now.

for group names, I've tried to maintain consistency within the same super group.
